local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint
  track_unkown_space: true
  update_frequency: 10.0
  publish_frequency: 5.0
  width: 10.0
  height: 10.0
  resolution: 0.05
  transform_tolerance: 0.5
  origin_x: -5
  origin_y: -5
  static_map: false
  rolling_window: true
  
  plugins:
    - {name: rgbd_obstacle_layer, type: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"}
    - {name: inflater_layer, type: "costmap_2d::InflationLayer"}

  inflater_layer:
    cost_scaling_factor: 8.0
    inflation_radius: 0.45
