TrajectoryPlannerROS:

  # Robot Configuration Parameters
  acc_lim_x: 2.0
  acc_lim_theta:  10

  max_vel_x: 1.2
  min_vel_x: -0.2

  max_vel_theta: 1.57
  min_vel_theta: -1.57
  min_in_place_vel_theta: 0.314

  holonomic_robot: false
  escape_vel: -0.3

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 3.14
  xy_goal_tolerance: 0.1
  latch_xy_goal_tolerance: false

  # Forward Simulation Parameters
  sim_time: 1.7
  sim_granularity: 0.025
  angular_sim_granularity: 0.02
  vx_samples: 6
  vy_samples: 0
  vtheta_samples: 20
  controller_frequency: 15.0

  # Trajectory scoring parameters
  meter_scoring: true # Whether the gdist_scale and pdist_scale parameters should assume that goal_distance and path_distance are expressed in units of meters or cells. Cells are assumed by default (false).
  occdist_scale: 0.05 #The weighting for how much the controller should attempt to avoid obstacles. default 0.01
  path_distance_bias: 1.2 #0.75  #     The weighting for how much the controller should stay close to the path it was given . default 0.6
  goal_distance_bias: 0.8 #1.0 #     The weighting for how much the controller should attempt to reach its local goal, also controls speed  default 0.8

  heading_lookahead: 1  #How far to look ahead in meters when scoring different in-place-rotation trajectories
  heading_scoring: true  #Whether to score based on the robot's heading to the path or its distance from the path. default false
  heading_scoring_timestep: 1   #How far to look ahead in time in seconds along the simulated trajectory when using heading scoring (double, default: 0.8)
  dwa: true #Whether to use the Dynamic Window Approach (DWA)_ or whether to use Trajectory Rollout
  simple_attractor: false
  publish_cost_grid_pc: true

  #Oscillation Prevention Parameters
  oscillation_reset_dist: 0.1 #How far the robot must travel in meters before oscillation flags are reset (double, default: 0.05)
  escape_reset_dist: 0.1
  escape_reset_theta: 0.1

DWAPlannerROS:
  acc_lim_theta: 10.0
  acc_lim_x: 5.0
  acc_lim_y: 0.0

  max_vel_theta: 1.57
  min_vel_theta: 0.4

  max_vel_x: 1.2
  min_vel_x: -0.2
  max_vel_y: 0.1
  min_vel_y: -0.1

  max_vel_trans: 0.7
  min_vel_trans: 0.1
  
  theta_stopped_vel: 0.3
  trans_stopped_vel: 0.3

  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 1.57
  latch_xy_goal_tolerance: false

  occdist_scale: 0.05

  forward_point_distance: 0.5
  path_distance_bias: 32.0
  goal_distance_bias: 24.0

  sim_granularity: 0.025
  sim_time: 2.0
  angular_sim_granularity: 0.1
  max_scaling_factor: 0.2
  scaling_speed: 0.25
  stop_time_buffer: 0.2

  oscillation_reset_dist: 0.2
  prune_plan: false

  twirling_scale: 0.0
  vx_samples: 6
  vy_samples: 1
  vth_samples: 20

  use_dwa: true

  publish_cost_grid: true
