shutdown_costmaps: false

recovery_behaviors: 
  - { name: conservative_reset, type: clear_costmap_recovery/ClearCostmapRecovery}
  - { name: rotate_recovery, type: rotate_recovery/RotateRecovery}
  - { name: aggressive_reset, type: clear_costmap_recovery/ClearCostmapRecovery} 

controller_frequency: 15.0
controller_patience: 10.0

planner_frequency: 5.0
planner_patience: 5.0

oscillation_timeout: 5.0
oscillation_distance: 0.5

max_planning_retries: 3

recovery_behavior_enabled: true
clearing_rotation_allowed: true
