frequency: 30
publish_tf: true
two_d_mode: true
transform_timeout: 0.5
use_control: true
control_timeout: 0.5
control_config: [true,  false, false,
                 false, false, true]
acceleration_limits: [1.1, 0.0, 0.0,
                      0.0, 0.0, 5.0]
deceleration_limits: [1.1, 0.0, 0.0,
                      0.0, 0.0, 5.0]

smooth_lagged_data: true
history_length: 0.2
dynamic_process_noise_covariance: true

reset_on_time_jump: true
print_diagnostics: true

odom0: /ubiquity_velocity_controller/odom
# X,Y,Z,roll,pitch,yaw,X˙,Y˙,Z˙,roll˙,pitch˙,yaw˙,X˙˙,Y˙˙,Z˙˙,roll˙˙,pitch˙˙,yaw˙˙
odom0_config: [false, false, false,
               false, false, false,
               true, true, false,
               false, false, true,
               false, false, false]
odom0_differential: false
odom0_relative: false
odom0_queue_size: 50


# odometry from GICP
odom1: /scan_matching_odometry/odom
# X,Y,Z,roll,pitch,yaw,X˙,Y˙,Z˙,roll˙,pitch˙,yaw˙,X˙˙,Y˙˙,Z˙˙,roll˙˙,pitch˙˙,yaw˙˙
odom1_config: [true, true, true,
               true, true, true,
               false, false, false,
               false, false, false,
               false, false, false]
odom1_differential: false
odom1_relative: true  
odom1_queue_size: 30


odom_frame: odom
world_frame: odom
# map_frame: map
base_link_frame: base_footprint