frequency: 100
two_d_mode: true

odom0: /ubiquity_velocity_controller/odom
# X,Y,Z,roll,pitch,yaw,X˙,Y˙,Z˙,roll˙,pitch˙,yaw˙
odom0_config: [false, false, false,
               false, false, false,
               true, true, false,
               false, false, true,
               false, false, false]
odom0_differential: false
odom0_relative: true

odom_frame: odom
base_link_frame: base_footprint
world_frame: odom