global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  track_unknown_space: true
  update_frequency: 5.0
  publish_frequency: 2.0
  width: 40.0
  height: 40.0
  resolution: 0.05
  origin_x: -20.0
  origin_y: -20.0
  rolling_window: false
  transform_tolerance: 0.5

  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}


  static_layer:
    map_topic: /projected_map
    trinary_costmap: true

  inflation_layer:
    cost_scaling_factor: 2.85
    inflation_radius: 1.5


    