local_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  # track_unkown_space: true
  update_frequency: 10.0
  publish_frequency: 5.0
  width: 5.0
  height: 5.0
  resolution: 0.05
  transform_tolerance: 0.5
  origin_x: -2.5
  origin_y: -2.5
  rolling_window: true
  
  plugins:
    - {name: rgbd_obstacle_layer, type: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  inflation_layer:
    cost_scaling_factor: 10.0
    inflation_radius: 0.45
